// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3dgsXGytqTyRk48gqhw06bbWGdLy3Yiw',
    appId: '1:271438819122:web:ea237544bad4ae0348712b',
    messagingSenderId: '271438819122',
    projectId: 'act13-24388',
    authDomain: 'act13-24388.firebaseapp.com',
    storageBucket: 'act13-24388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGPaSSGvt3N74zCkWvdtJcswfrEjpZ0o',
    appId: '1:271438819122:android:6a4b557b538fc2e348712b',
    messagingSenderId: '271438819122',
    projectId: 'act13-24388',
    storageBucket: 'act13-24388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRSBqSZk37FKdxS_-F9Tx5MGUBM9Ug4Jg',
    appId: '1:271438819122:ios:ef134fd9243f9db548712b',
    messagingSenderId: '271438819122',
    projectId: 'act13-24388',
    storageBucket: 'act13-24388.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRSBqSZk37FKdxS_-F9Tx5MGUBM9Ug4Jg',
    appId: '1:271438819122:ios:ef134fd9243f9db548712b',
    messagingSenderId: '271438819122',
    projectId: 'act13-24388',
    storageBucket: 'act13-24388.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3dgsXGytqTyRk48gqhw06bbWGdLy3Yiw',
    appId: '1:271438819122:web:b6f1ff2d2e7158a848712b',
    messagingSenderId: '271438819122',
    projectId: 'act13-24388',
    authDomain: 'act13-24388.firebaseapp.com',
    storageBucket: 'act13-24388.firebasestorage.app',
  );
}
